### ISSUE TITLE
TypeError: '_NamespacePath' object is not subscriptable

### ISSUE THREAD

**Issue by zwacm** [allenai/scibert#49]
when I finished  the previous work mentioned aboved, I encountered the problem:
src/allennlp/allennlp/common/util.py  line316, in import_submodules
    path_string = ' ' if not path else path[0] 
TypeError: '_NamespacePath' object is not subscriptable.....

what should I do to deal with the problem?? Thanks in advance

**Comment by 393301836** [comment]
from allennlp.commands import main  # pylint: disable=wrong-import-position

**Comment by kyleclo** [comment]
Can you past the command you're executing for AllenNLP?  Are you including a `--include-package` argument?

**Comment by 393301836** [comment]
Thank you for your response! Do you mean that I have to Install AllenNLP package apart from " ip install -r requirements.txt"?   By the way, the problem appears when I just follow the tips on Readme.txt, so what should I do in addition to these tips?

**Comment by 393301836** [comment]
Thank you for your response! Do you mean that I have to Install AllenNLP package apart from " pip install -r requirements.txt"? By the way, the problem appears when I just follow the tips on Readme.txt, so what should I do in addition to these tips?

**Comment by kyleclo** [comment]
Hi, I meant to ask what commands are you executing such that you encounter the error?  Can you paste the full commands you're using?

**Comment by 393301836** [comment]
Thank you! I pass "sh ./scibert/scripts/train_allennlp_local.sh ./scibert/output" to run the script as the final tips, and my env is python3.6.8. So is it something wrong with the Allennlp source code?

**Comment by 393301836** [comment]
after I fix the problem by adding empty "__init__" file to the root dictory, there raise the allennlp configurationError, as following:
     allennlp.common.checks.ConfigurationError: 'Cannot register text_classifier as Model; name already in use for TextClassifier'.
triggered by "from models.text_classifier import TextClassifier".

**Comment by kyleclo** [comment]
> Thank you! I pass "sh ./scibert/scripts/train_allennlp_local.sh ./scibert/output" to run the script as the final tips, and my env is python3.6.8. So is it something wrong with the Allennlp source code?

Ah I see.  I don't recommend using that script; we used that for our internal experiments, but it's not meant for outside usage.  For example, the paths specified in that script are specific to our machines, so the script would need to be modified for others.

The best way to use SciBERT is how you'd normally use BERT.  Have you tried using BERT with AllenNLP?  If you can get that to work, then simply changing the path to BERT weights to SciBERT weights will make sure everything works.

Can you describe what it is you're trying to do?  For example, do you already have a BERT-based model and want to swap in SciBERT?  Are you working with a particular AllenNLP model in mind, or are you trying to use the ones that are in this repo?

**Comment by 393301836** [comment]
Thanks, I have never used BERT and AllenNLP model before, and I just want to use the trained scibert models download from the repo that you given. So what can I do to run the scibert traind models to produce the result as you described in the paper besides following the tips in the Readme text strictly. Any advice will be appreciated.

**Comment by kyleclo** [comment]
I understand now, thanks!  We released SciBERT tensorflow/pytorch weights with the intention that researchers would use them within their existing tensorflow/pytorch projects that already know how to consume BERT.  It's fine if you haven't used AllenNLP before, but it's a bit hard to help you unless you have an existing project based around BERT already.  

If you haven't already picked up a modeling framework, I recommend adopting AllenNLP and going through the tutorial first.  Once you have an environment setup that can successfully train *any* AllenNLP model, it should be straightforward to help you pick the specific model you're interested in & get the SciBERT weights plugged in.

**Comment by zwacm** [comment]
Hi @ @kyleclo,
 I tried to run the code and solve the problem above, however, another problem still stops me,[https://github.com/allenai/allennlp/issues/3134](url) . 

Whether there are some points I may miss?
Thank you!

**Comment by zwacm** [comment]
After solving Cuda Error : RuntimeError: CUDNN_STATUS_EXECUTION_FAILED [https://discuss.pytorch.org/t/cuda-error-runtimeerror-cudnn-status-execution-failed/17625](url), I run the code finally.

Thank you all.
